version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
    container_name: autoremove_torrents
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

